// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh8BMOYPuLj9O8A5v9pCUHEEUezIX2X90',
    appId: '1:232150582203:web:c3f9ca57f880919b5afa9e',
    messagingSenderId: '232150582203',
    projectId: 'iwin-58f4b',
    authDomain: 'iwin-58f4b.firebaseapp.com',
    storageBucket: 'iwin-58f4b.firebasestorage.app',
    measurementId: 'G-NDYKEZPPL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqAReSvFIZ86eqqnWOKvypxtfm0KXch1E',
    appId: '1:232150582203:android:579c0c757c2d9d8d5afa9e',
    messagingSenderId: '232150582203',
    projectId: 'iwin-58f4b',
    storageBucket: 'iwin-58f4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-t2H7Zbo26y9zCFF6lV183wBkhdoJj0',
    appId: '1:232150582203:ios:ad0fa777dc922f6e5afa9e',
    messagingSenderId: '232150582203',
    projectId: 'iwin-58f4b',
    storageBucket: 'iwin-58f4b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-t2H7Zbo26y9zCFF6lV183wBkhdoJj0',
    appId: '1:232150582203:ios:ad0fa777dc922f6e5afa9e',
    messagingSenderId: '232150582203',
    projectId: 'iwin-58f4b',
    storageBucket: 'iwin-58f4b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh8BMOYPuLj9O8A5v9pCUHEEUezIX2X90',
    appId: '1:232150582203:web:1694ba26b4ad7d9c5afa9e',
    messagingSenderId: '232150582203',
    projectId: 'iwin-58f4b',
    authDomain: 'iwin-58f4b.firebaseapp.com',
    storageBucket: 'iwin-58f4b.firebasestorage.app',
    measurementId: 'G-9W36KQFW2D',
  );
}
